[app]
app1 ansible_host=18.215.33.6 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ahmad/ansible/ansible.pem

[db]
db1 ansible_host=32.196.137.140 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ahmad/ansible/ansible.pem
